const solver = require("./21i");

const input = `...........
.....###.#.
.###.##..#.
..#.#...#..
....#.#....
.##..S####.
.##..#...#.
.......##..
.##.#.####.
.##..##.##.
...........`;

const emptyInput = `...........
...........
...........
...........
...........
.....S.....
...........
...........
...........
...........
...........`;

describe("21i", () => {
  it("example", () => {
    solver(input, 6).should.equal(16);
  });

  it("with empty field", () => {
    solver(emptyInput, 1).should.equal(4);
    solver(emptyInput, 2).should.equal(9);
    solver(emptyInput, 3).should.equal(16);
    solver(emptyInput, 4).should.equal(25);
  });
});
